Repository NBCAMP-EZPZ/EZPZ-User, pull requests merged in 2024-07, with the labels that each got.

#12 Feat/coupon
  src/main/java/com/sparta/ezpzuser/common/config/PageConfig.java
  src/main/java/com/sparta/ezpzuser/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/common/resolver/CustomPageableHandlerMethodArgumentResolver.java
  src/main/java/com/sparta/ezpzuser/common/util/PageUtil.java
  src/main/java/com/sparta/ezpzuser/common/util/RepositoryUtil.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/controller/CouponController.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/dto/UserCouponResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/entity/Coupon.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/entity/UserCoupon.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/repository/CouponRepository.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/repository/UserCouponRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/repository/UserCouponRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/service/CouponService.java
  src/main/java/com/sparta/ezpzuser/domain/user/dto/SignupRequestDto.java
Labels: feat ✨, P0

#7 Feat/reservation
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/domain/host/entity/Host.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzuser/domain/popup/enums/ApprovalStatus.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/dto/ReservationRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/enums/ReservationStatus.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/ezpzuser/domain/slot/controller/SlotController.java
  src/main/java/com/sparta/ezpzuser/domain/slot/dto/SlotResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/slot/entity/Slot.java
  src/main/java/com/sparta/ezpzuser/domain/slot/enums/SlotStatus.java
  src/main/java/com/sparta/ezpzuser/domain/slot/repository/SlotRepository.java
  src/main/java/com/sparta/ezpzuser/domain/slot/service/SlotService.java
  src/main/java/com/sparta/ezpzuser/domain/user/entity/User.java
Labels: feat ✨, P0

#10 Feat/popup
  http/http-client.env.json
  http/popup.http
  http/user.http
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/domain/host/entity/Host.java
  src/main/java/com/sparta/ezpzuser/domain/popup/controller/PopupController.java
  src/main/java/com/sparta/ezpzuser/domain/popup/dto/PopupCondition.java
  src/main/java/com/sparta/ezpzuser/domain/popup/dto/PopupPageResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/popup/dto/PopupResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Image.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Likes.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzuser/domain/popup/enums/ApprovalStatus.java
  src/main/java/com/sparta/ezpzuser/domain/popup/enums/PopupStatus.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/ImageRepository.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepository.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/popup/service/ImageService.java
  src/main/java/com/sparta/ezpzuser/domain/popup/service/PopupService.java
  src/main/java/com/sparta/ezpzuser/domain/user/dto/SignupRequestDto.java
Labels: feat ✨

#17 Feat/reservation (예약 조회 & 예약 취소)
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/repository/ReservationRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/ezpzuser/domain/slot/controller/SlotController.java
  src/main/java/com/sparta/ezpzuser/domain/slot/entity/Slot.java
  src/main/java/com/sparta/ezpzuser/domain/slot/repository/SlotRepository.java
  src/main/java/com/sparta/ezpzuser/domain/slot/repository/SlotRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/slot/repository/SlotRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/slot/service/SlotService.java
Labels: feat ✨, refactor 🔧, P0

#22 Feat/굿즈
  http/item.http
  src/main/java/com/sparta/ezpzuser/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/domain/item/controller/ItemController.java
  src/main/java/com/sparta/ezpzuser/domain/item/dto/ItemCondition.java
  src/main/java/com/sparta/ezpzuser/domain/item/dto/ItemPageResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/item/dto/ItemResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/item/entity/Item.java
  src/main/java/com/sparta/ezpzuser/domain/item/enums/ItemStatus.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepository.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/item/service/ItemService.java
  src/main/java/com/sparta/ezpzuser/domain/popup/dto/PopupPageResponseDto.java
Labels: feat ✨

#21 Feat/review
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/common/util/RepositoryUtil.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/repository/UserCouponRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/PopupRepository.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/PopupRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/PopupRepositoryImpl.java
  src/main/java/com/sparta/ezpzuser/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/ezpzuser/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/review/entity/Review.java
  src/main/java/com/sparta/ezpzuser/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/ezpzuser/domain/review/service/ReviewService.java
Labels: feat ✨, P1

#24 Feat/좋아요
  http/like.http
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/domain/item/entity/Item.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/like/controller/LikeController.java
  src/main/java/com/sparta/ezpzuser/domain/like/dto/LikeContentDto.java
  src/main/java/com/sparta/ezpzuser/domain/like/dto/LikeItemPageResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/like/dto/LikePopupPageResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/like/entity/Like.java
  src/main/java/com/sparta/ezpzuser/domain/like/repository/LikeRepository.java
  src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
  src/main/java/com/sparta/ezpzuser/domain/popup/controller/PopupController.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Likes.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/PopupRepository.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/PopupRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/PopupRepositoryImpl.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepository.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/review/service/ReviewService.java
  src/main/java/com/sparta/ezpzuser/domain/user/entity/User.java
Labels: feat ✨

#25 Feat/장바구니, 주문
  http/cart.http
  http/http-client.env.json
  http/user.http
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/domain/cart/controller/CartController.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartCreateRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartUpdateRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/entity/Cart.java
  src/main/java/com/sparta/ezpzuser/domain/cart/repository/CartRepository.java
  src/main/java/com/sparta/ezpzuser/domain/cart/service/CartService.java
  src/main/java/com/sparta/ezpzuser/domain/item/entity/Item.java
  src/main/java/com/sparta/ezpzuser/domain/item/service/ItemService.java
  src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
  src/main/java/com/sparta/ezpzuser/domain/order/controller/OrderController.java
  src/main/java/com/sparta/ezpzuser/domain/order/dto/OrderFindAllResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/order/dto/OrderRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/order/dto/OrderResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/order/entity/Order.java
  src/main/java/com/sparta/ezpzuser/domain/order/enums/OrderStatus.java
  src/main/java/com/sparta/ezpzuser/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/ezpzuser/domain/order/service/OrderService.java
  src/main/java/com/sparta/ezpzuser/domain/orderline/dto/OrderlineResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/orderline/entity/Orderline.java
  src/main/java/com/sparta/ezpzuser/domain/orderline/repository/OrderlineRepository.java
  src/main/java/com/sparta/ezpzuser/domain/popup/service/PopupService.java
Labels: feat ✨, P0

#29 feat [#28] : AOP
  build.gradle
  http/like.http
  http/popup.http
  src/main/java/com/sparta/ezpzuser/common/aop/LogAspect.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/popup/dto/PopupPageResponseDto.java
Labels: feat ✨

#31 Test/orders
  src/main/java/com/sparta/ezpzuser/domain/host/entity/Host.java
  src/main/java/com/sparta/ezpzuser/domain/item/entity/Item.java
  src/main/java/com/sparta/ezpzuser/domain/order/dto/OrderFindAllResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/order/dto/OrderRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/order/dto/OrderResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/order/entity/Order.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzuser/domain/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/user/entity/User.java
  src/test/java/com/sparta/ezpzuser/EzpzUserApplicationTests.java
  src/test/java/com/sparta/ezpzuser/domain/order/service/OrderServiceTest.java
Labels: P0, test 🧨

#35 test [#34] : 좋아요 동시성 테스트
  build.gradle
  http/http-client.env.json
  http/user.http
  src/main/java/com/sparta/ezpzuser/domain/host/repository/HostRepository.java
  src/main/java/com/sparta/ezpzuser/domain/item/entity/Item.java
  src/main/java/com/sparta/ezpzuser/domain/like/dto/LikeContentDto.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Image.java
  src/main/java/com/sparta/ezpzuser/domain/user/entity/User.java
  src/main/resources/application.yml
  src/test/java/com/sparta/ezpzuser/domain/like/service/LikeServiceTest.java
  src/test/resources/application.yml
Labels: test 🧨

#40 Feat/redis cache (캐시 처리 초기 설정)
  src/main/java/com/sparta/ezpzuser/common/config/RedisCacheConfig.java
  src/main/java/com/sparta/ezpzuser/common/entity/RestPage.java
Labels: feat ✨, optimization 💻
