Repository NBCAMP-EZPZ/EZPZ-User, pull requests merged in 2024-08, with the labels that each got.

#47 Feat [#46] : 팝업 리뷰 개수, 평균 별점 기능 추가
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzuser/domain/review/entity/Review.java
Labels: feat ✨

#38 Test/reservation concurrency test (예약 동시성 테스트)
  src/main/java/com/sparta/ezpzuser/domain/host/entity/Host.java
  src/main/java/com/sparta/ezpzuser/domain/host/repository/HostRepository.java
  src/main/java/com/sparta/ezpzuser/domain/popup/entity/Popup.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/ezpzuser/domain/slot/repository/SlotRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/user/entity/User.java
  src/test/java/com/sparta/ezpzuser/domain/reservation/service/ReservationConcurrencyTest.java
  src/test/resources/application.yml
Labels: P0, test 🧨

#42 Test/coupon
  build.gradle
  src/main/java/com/sparta/ezpzuser/common/config/RedisCacheConfig.java
  src/main/java/com/sparta/ezpzuser/common/config/redis/RedisCacheConfig.java
  src/main/java/com/sparta/ezpzuser/common/config/redis/RedisClusterConfig.java
  src/main/java/com/sparta/ezpzuser/common/config/redis/RedisClusterProperties.java
  src/main/java/com/sparta/ezpzuser/common/config/redis/RedissonConfig.java
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/common/lock/DistributedLock.java
  src/main/java/com/sparta/ezpzuser/common/lock/DistributedLockAspect.java
  src/main/java/com/sparta/ezpzuser/common/lock/TransactionForAop.java
  src/main/java/com/sparta/ezpzuser/common/util/CustomSpELParser.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/entity/Coupon.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/service/CouponService.java
  src/main/java/com/sparta/ezpzuser/domain/user/dto/SignupRequestDto.java
  src/main/resources/application.yml
  src/test/java/com/sparta/ezpzuser/EzpzUserApplicationTests.java
  src/test/java/com/sparta/ezpzuser/domain/coupon/service/CouponConcurrencyTest.java
  src/test/resources/application.yml
Labels: feat ✨

#45 Bug/front
  src/main/java/com/sparta/ezpzuser/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/repository/CartRepository.java
  src/main/java/com/sparta/ezpzuser/domain/item/controller/ItemController.java
  src/main/java/com/sparta/ezpzuser/domain/item/dto/ItemCondition.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/review/service/ReviewService.java
Labels: bug 🐛, refactor 🔧

#43 Feat/reservation optimization
  src/main/java/com/sparta/ezpzuser/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/entity/Reservation.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/repository/ReservationRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/ezpzuser/domain/slot/dto/SlotResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/slot/entity/Slot.java
  src/test/java/com/sparta/ezpzuser/domain/reservation/service/ReservationServiceTest.java
Labels: refactor 🔧, P0, optimization 💻

#50 Bug/build
  src/main/java/com/sparta/ezpzuser/domain/user/entity/User.java
  src/test/java/com/sparta/ezpzuser/domain/like/service/LikeServiceTest.java
  src/test/java/com/sparta/ezpzuser/domain/order/service/OrderServiceTest.java
Labels: bug 🐛

#79 LikeService, ReservationService Refactor
  http/like.http
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/domain/cart/controller/CartController.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartCreateResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/service/CartService.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/coupon/dto/UserCouponResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/like/dto/LikeResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/like/entity/Like.java
  src/main/java/com/sparta/ezpzuser/domain/like/service/LikeService.java
  src/main/java/com/sparta/ezpzuser/domain/order/service/OrderService.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/dto/ReservationRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/ezpzuser/domain/slot/entity/Slot.java
  src/main/java/com/sparta/ezpzuser/domain/slot/enums/SlotStatus.java
  src/main/java/com/sparta/ezpzuser/domain/slot/repository/SlotRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/user/entity/User.java
  src/test/java/com/sparta/ezpzuser/domain/coupon/service/CouponConcurrencyTest.java
  src/test/java/com/sparta/ezpzuser/domain/reservation/service/ReservationConcurrencyTest.java
  src/test/java/com/sparta/ezpzuser/domain/reservation/service/ReservationServiceUnitTest.java
  src/test/resources/application.yml
Labels: refactor 🔧

#85 Refactor
  http/cart.http
  http/coupon.http
  http/item.http
  http/order.http
  http/popup.http
  http/reservation.http
  http/review.http
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/domain/cart/controller/CartController.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartCreateRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartCreateResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartListResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/dto/CartUpdateRequestDto.java
  src/main/java/com/sparta/ezpzuser/domain/cart/service/CartService.java
  src/main/java/com/sparta/ezpzuser/domain/item/controller/ItemController.java
  src/main/java/com/sparta/ezpzuser/domain/item/dto/ItemCondition.java
  src/main/java/com/sparta/ezpzuser/domain/item/dto/ItemResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/item/service/ItemService.java
  src/main/java/com/sparta/ezpzuser/domain/order/dto/OrderPageResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/order/dto/OrderResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/order/dto/OrderlineResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/ezpzuser/domain/order/service/OrderService.java
  src/main/java/com/sparta/ezpzuser/domain/popup/controller/PopupController.java
  src/main/java/com/sparta/ezpzuser/domain/popup/dto/PopupCondition.java
  src/main/java/com/sparta/ezpzuser/domain/popup/dto/PopupPageResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/popup/dto/PopupResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/popup/repository/popup/PopupRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/popup/service/PopupService.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/controller/ReservationController.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/dto/ReservationResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/sparta/ezpzuser/domain/reservation/service/ReservationService.java
  src/main/java/com/sparta/ezpzuser/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/ezpzuser/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/review/repository/ReviewRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/review/service/ReviewService.java
  src/main/java/com/sparta/ezpzuser/domain/slot/controller/SlotController.java
  src/main/java/com/sparta/ezpzuser/domain/slot/dto/SlotResponseDto.java
  src/main/java/com/sparta/ezpzuser/domain/slot/repository/SlotRepository.java
  src/main/java/com/sparta/ezpzuser/domain/slot/repository/SlotRepositoryCustom.java
  src/main/java/com/sparta/ezpzuser/domain/slot/repository/SlotRepositoryCustomImpl.java
  src/main/java/com/sparta/ezpzuser/domain/slot/service/SlotService.java
Labels: refactor 🔧

#90 Refactor/item
  src/main/java/com/sparta/ezpzuser/domain/item/entity/Item.java
Labels: refactor 🔧

#118 Fix : TimeZone Asia/Seoul로 변경
  src/main/resources/application.yml
Labels: bug 🐛

#121 Bug : 0명도 예약 되는 버그 해결
  src/main/java/com/sparta/ezpzuser/common/exception/ErrorType.java
  src/main/java/com/sparta/ezpzuser/domain/slot/entity/Slot.java
Labels: bug 🐛
